#############################################################################
# Makefile for building: SilnySolverGUI
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  SilnySolverGUI.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -o Makefile SilnySolverGUI.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -std=c++0x -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../Dev/inc -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = SilnySolverGUI1.0.0
DISTDIR = /home/optimus/repo/SilnySolverBackup/SilnySolver/SilnySolverUI/.tmp/SilnySolverGUI1.0.0
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS) -L/usr/X11R6/lib64 -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/mainwindow.cpp \
		../Dev/src/CrazyCube.cpp \
		../Dev/src/CrazyCubeAbstract.cpp \
		../Dev/src/CrazyCubeCache.cpp \
		../Dev/src/CrazyCubeImproved.cpp \
		../Dev/src/CrazyCubeSolver.cpp \
		../Dev/src/FileReader.cpp \
		../Dev/src/FileWriter.cpp \
		../Dev/src/CrazyCubePruner.cpp \
		../Dev/src/CrazyCubeMapper.cpp \
		../Dev/src/OuterCornersMapGenerator.cpp \
		../Dev/src/MoveMapsGeneratorI.cpp \
		../Dev/src/CrazyCubeMoveMapper.cpp \
		src/camera3d.cpp \
		src/input.cpp \
		src/transform3d.cpp \
		src/glview.cpp \
		build-SilnySolverGUI-Desktop-Debug/moc_glview.cpp \
		build-SilnySolverGUI-Desktop-Debug/moc_mainwindow.cpp moc_mainwindow.cpp \
		moc_glview.cpp
OBJECTS       = main.o \
		mainwindow.o \
		CrazyCube.o \
		CrazyCubeAbstract.o \
		CrazyCubeCache.o \
		CrazyCubeImproved.o \
		CrazyCubeSolver.o \
		FileReader.o \
		FileWriter.o \
		CrazyCubePruner.o \
		CrazyCubeMapper.o \
		OuterCornersMapGenerator.o \
		MoveMapsGeneratorI.o \
		CrazyCubeMoveMapper.o \
		camera3d.o \
		input.o \
		transform3d.o \
		glview.o \
		moc_glview.o \
		moc_mainwindow.o \
		moc_mainwindow.o \
		moc_glview.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++11.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		SilnySolverGUI.pro inc/mainwindow.h \
		inc/camera3d.h \
		inc/transform3d.h \
		inc/input.h \
		inc/vertex.h \
		inc/glview.h \
		build-SilnySolverGUI-Desktop-Debug/ui_mainwindow.h src/main.cpp \
		src/mainwindow.cpp \
		../Dev/src/CrazyCube.cpp \
		../Dev/src/CrazyCubeAbstract.cpp \
		../Dev/src/CrazyCubeCache.cpp \
		../Dev/src/CrazyCubeImproved.cpp \
		../Dev/src/CrazyCubeSolver.cpp \
		../Dev/src/FileReader.cpp \
		../Dev/src/FileWriter.cpp \
		../Dev/src/CrazyCubePruner.cpp \
		../Dev/src/CrazyCubeMapper.cpp \
		../Dev/src/OuterCornersMapGenerator.cpp \
		../Dev/src/MoveMapsGeneratorI.cpp \
		../Dev/src/CrazyCubeMoveMapper.cpp \
		src/camera3d.cpp \
		src/input.cpp \
		src/transform3d.cpp \
		src/glview.cpp \
		build-SilnySolverGUI-Desktop-Debug/moc_glview.cpp \
		build-SilnySolverGUI-Desktop-Debug/moc_mainwindow.cpp
QMAKE_TARGET  = SilnySolverGUI
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = SilnySolverGUI


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: SilnySolverGUI.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++11.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		SilnySolverGUI.pro \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile SilnySolverGUI.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++11.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
SilnySolverGUI.pro:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile SilnySolverGUI.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents inc/mainwindow.h inc/camera3d.h inc/transform3d.h inc/input.h inc/vertex.h inc/glview.h build-SilnySolverGUI-Desktop-Debug/ui_mainwindow.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/mainwindow.cpp ../Dev/src/CrazyCube.cpp ../Dev/src/CrazyCubeAbstract.cpp ../Dev/src/CrazyCubeCache.cpp ../Dev/src/CrazyCubeImproved.cpp ../Dev/src/CrazyCubeSolver.cpp ../Dev/src/FileReader.cpp ../Dev/src/FileWriter.cpp ../Dev/src/CrazyCubePruner.cpp ../Dev/src/CrazyCubeMapper.cpp ../Dev/src/OuterCornersMapGenerator.cpp ../Dev/src/MoveMapsGeneratorI.cpp ../Dev/src/CrazyCubeMoveMapper.cpp src/camera3d.cpp src/input.cpp src/transform3d.cpp src/glview.cpp build-SilnySolverGUI-Desktop-Debug/moc_glview.cpp build-SilnySolverGUI-Desktop-Debug/moc_mainwindow.cpp $(DISTDIR)/
	$(COPY_FILE) --parents design/mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp moc_glview.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_glview.cpp
moc_mainwindow.cpp: ../Dev/inc/CrazyCubeSolver.h \
		../Dev/inc/CrazyCube.h \
		../Dev/inc/CrazyCubeBase.h \
		../Dev/inc/CrazyCubeAbstract.h \
		../Dev/inc/CrazyCubeSolverParametersD.h \
		inc/mainwindow.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/optimus/repo/SilnySolverBackup/SilnySolver/SilnySolverUI -I/home/optimus/repo/SilnySolverBackup/SilnySolver/Dev/inc -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include inc/mainwindow.h -o moc_mainwindow.cpp

moc_glview.cpp: inc/transform3d.h \
		inc/camera3d.h \
		inc/glview.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/optimus/repo/SilnySolverBackup/SilnySolver/SilnySolverUI -I/home/optimus/repo/SilnySolverBackup/SilnySolver/Dev/inc -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include inc/glview.h -o moc_glview.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: design/mainwindow.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic design/mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: src/main.cpp inc/mainwindow.h \
		../Dev/inc/CrazyCubeSolver.h \
		../Dev/inc/CrazyCube.h \
		../Dev/inc/CrazyCubeBase.h \
		../Dev/inc/CrazyCubeAbstract.h \
		../Dev/inc/CrazyCubeSolverParametersD.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

mainwindow.o: src/mainwindow.cpp inc/mainwindow.h \
		../Dev/inc/CrazyCubeSolver.h \
		../Dev/inc/CrazyCube.h \
		../Dev/inc/CrazyCubeBase.h \
		../Dev/inc/CrazyCubeAbstract.h \
		../Dev/inc/CrazyCubeSolverParametersD.h \
		ui_mainwindow.h \
		../Dev/inc/CrazyCubeImproved.h \
		../Dev/inc/CrazyCubeCache.h \
		../Dev/inc/CrazyCubeMapper.h \
		../Dev/inc/CrazyCubeMoveMapper.h \
		../Dev/inc/OuterCornersMapGenerator.h \
		../Dev/inc/MoveMapsGeneratorI.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o src/mainwindow.cpp

CrazyCube.o: ../Dev/src/CrazyCube.cpp ../Dev/inc/CrazyCube.h \
		../Dev/inc/CrazyCubeBase.h \
		../Dev/inc/CrazyCubeAbstract.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CrazyCube.o ../Dev/src/CrazyCube.cpp

CrazyCubeAbstract.o: ../Dev/src/CrazyCubeAbstract.cpp ../Dev/inc/CrazyCubeAbstract.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CrazyCubeAbstract.o ../Dev/src/CrazyCubeAbstract.cpp

CrazyCubeCache.o: ../Dev/src/CrazyCubeCache.cpp ../Dev/inc/CrazyCubeCache.h \
		../Dev/inc/CrazyCubeAbstract.h \
		../Dev/inc/CrazyCubeMapper.h \
		../Dev/inc/CrazyCube.h \
		../Dev/inc/CrazyCubeBase.h \
		../Dev/inc/CrazyCubeMoveMapper.h \
		../Dev/inc/OuterCornersMapGenerator.h \
		../Dev/inc/MoveMapsGeneratorI.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CrazyCubeCache.o ../Dev/src/CrazyCubeCache.cpp

CrazyCubeImproved.o: ../Dev/src/CrazyCubeImproved.cpp ../Dev/inc/CrazyCubeImproved.h \
		../Dev/inc/CrazyCubeBase.h \
		../Dev/inc/CrazyCubeAbstract.h \
		../Dev/inc/CrazyCubeCache.h \
		../Dev/inc/CrazyCubeMapper.h \
		../Dev/inc/CrazyCube.h \
		../Dev/inc/CrazyCubeMoveMapper.h \
		../Dev/inc/OuterCornersMapGenerator.h \
		../Dev/inc/MoveMapsGeneratorI.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CrazyCubeImproved.o ../Dev/src/CrazyCubeImproved.cpp

CrazyCubeSolver.o: ../Dev/src/CrazyCubeSolver.cpp ../Dev/inc/CrazyCubeSolver.h \
		../Dev/inc/CrazyCube.h \
		../Dev/inc/CrazyCubeBase.h \
		../Dev/inc/CrazyCubeAbstract.h \
		../Dev/inc/CrazyCubeSolverParametersD.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CrazyCubeSolver.o ../Dev/src/CrazyCubeSolver.cpp

FileReader.o: ../Dev/src/FileReader.cpp ../Dev/inc/FileReader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FileReader.o ../Dev/src/FileReader.cpp

FileWriter.o: ../Dev/src/FileWriter.cpp ../Dev/inc/FileWriter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FileWriter.o ../Dev/src/FileWriter.cpp

CrazyCubePruner.o: ../Dev/src/CrazyCubePruner.cpp ../Dev/inc/CrazyCubePruner.h \
		../Dev/inc/CrazyCubeAbstract.h \
		../Dev/inc/CrazyCubeMoveMapper.h \
		../Dev/inc/CrazyCube.h \
		../Dev/inc/CrazyCubeBase.h \
		../Dev/inc/OuterCornersMapGenerator.h \
		../Dev/inc/MoveMapsGeneratorI.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CrazyCubePruner.o ../Dev/src/CrazyCubePruner.cpp

CrazyCubeMapper.o: ../Dev/src/CrazyCubeMapper.cpp ../Dev/inc/CrazyCubeMapper.h \
		../Dev/inc/CrazyCube.h \
		../Dev/inc/CrazyCubeBase.h \
		../Dev/inc/CrazyCubeAbstract.h \
		../Dev/inc/CrazyCubeCache.h \
		../Dev/inc/CrazyCubeMoveMapper.h \
		../Dev/inc/OuterCornersMapGenerator.h \
		../Dev/inc/MoveMapsGeneratorI.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CrazyCubeMapper.o ../Dev/src/CrazyCubeMapper.cpp

OuterCornersMapGenerator.o: ../Dev/src/OuterCornersMapGenerator.cpp ../Dev/inc/OuterCornersMapGenerator.h \
		../Dev/inc/MoveMapsGeneratorI.h \
		../Dev/inc/CrazyCubeAbstract.h \
		../Dev/inc/CrazyCube.h \
		../Dev/inc/CrazyCubeBase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o OuterCornersMapGenerator.o ../Dev/src/OuterCornersMapGenerator.cpp

MoveMapsGeneratorI.o: ../Dev/src/MoveMapsGeneratorI.cpp ../Dev/inc/MoveMapsGeneratorI.h \
		../Dev/inc/CrazyCubeAbstract.h \
		../Dev/inc/CrazyCube.h \
		../Dev/inc/CrazyCubeBase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MoveMapsGeneratorI.o ../Dev/src/MoveMapsGeneratorI.cpp

CrazyCubeMoveMapper.o: ../Dev/src/CrazyCubeMoveMapper.cpp ../Dev/inc/CrazyCubeMoveMapper.h \
		../Dev/inc/CrazyCubeAbstract.h \
		../Dev/inc/CrazyCube.h \
		../Dev/inc/CrazyCubeBase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CrazyCubeMoveMapper.o ../Dev/src/CrazyCubeMoveMapper.cpp

camera3d.o: src/camera3d.cpp inc/camera3d.h \
		inc/transform3d.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o camera3d.o src/camera3d.cpp

input.o: src/input.cpp inc/input.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o input.o src/input.cpp

transform3d.o: src/transform3d.cpp inc/transform3d.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o transform3d.o src/transform3d.cpp

glview.o: src/glview.cpp inc/glview.h \
		inc/transform3d.h \
		inc/camera3d.h \
		inc/vertex.h \
		inc/input.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o glview.o src/glview.cpp

moc_glview.o: build-SilnySolverGUI-Desktop-Debug/moc_glview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_glview.o build-SilnySolverGUI-Desktop-Debug/moc_glview.cpp

moc_mainwindow.o: build-SilnySolverGUI-Desktop-Debug/moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o build-SilnySolverGUI-Desktop-Debug/moc_mainwindow.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_glview.o: moc_glview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_glview.o moc_glview.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

